services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - URL=mongodb://mongodb:27017/blog_db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
      - ENV=production
      - MONGO_DATABASE=blog_db
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blog_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 