services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a local MongoDB instance for development/testing
  # Uncomment the following service if you want to use local MongoDB instead of Atlas
  # mongodb:
  #   image: mongo:7.0
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  #     - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - blog-network

networks:
  blog-network:
    driver: bridge

# Uncomment if using local MongoDB
# volumes:
#   mongodb_data:
