name: Go Mock Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.3" # or your Go version

      - name: Run Mock Unit Tests Only
        run: |
          # Run all tests excluding integration tests
          go test ./... -v
